### PR TITLE
Update Docker code to match live

### PR DESCRIPTION
**Pull request by BenHall**
Updates for #61

### CODE REVIEW

**Comment by BenHall** [comment]
Thanks @ahmetb

**Comment by ahmetb** [comment]
Do you mind removing v1 and v2 distinction, I think we only need one version, that can reside in code/.

**Comment by BenHall** [comment]
v1/v2 are different. They output a different message to help users understanding rolling out Kubernetes changes

**Comment by ahmetb** [comment]
Ah, understood. Do you want me to push both :v1 and :v2.

**Comment by BenHall** [comment]
Yes please. I've updated both v1 and v2 to match what's currently live.

**Comment by ahmetb** [comment]
Will do. Feel free to merge the PR.

**Pull request closed without merging**
